// LaTeX CV Generator for ZenResume
// Generates LaTeX code based on the Northeastern University faculty CV template

interface PersonalInfo {
  fullName: string;
  email: string;
  phone: string;
  location: string;
  title: string;
  summary: string;
}

interface Experience {
  id: string;
  company: string;
  position: string;
  startDate: string;
  endDate: string;
  description: string;
}

interface Education {
  id: string;
  school: string;
  degree: string;
  field: string;
  graduationDate: string;
}

interface Publication {
  id: string;
  type: string;
  citation: string;
}

interface CreativeWork {
  id: string;
  type: string;
  description: string;
}

interface Grant {
  id: string;
  type: string;
  status: string;
  title: string;
  agency: string;
  role: string;
  effort: string;
  budget: string;
  period: string;
}

interface Teaching {
  id: string;
  type: string;
  title: string;
  details: string;
}

interface SectionTitles {
  education: string;
  publications: string;
  creativeActivity: string;
  grants: string;
  teaching: string;
  service: string;
}

export function generateLatex(data: {
  personalInfo: PersonalInfo;
  experiences: Experience[];
  education: Education[];
  publications: Publication[];
  creativeWorks: CreativeWork[];
  grants: Grant[];
  teachingEntries: Teaching[];
  sectionTitles: SectionTitles;
}): string {
  const { personalInfo, experiences, education, publications, creativeWorks, grants, teachingEntries, sectionTitles } = data;

  // Escape special LaTeX characters
  const escapeLatex = (text: string): string => {
    if (!text) return '';
    return text
      .replace(/\\/g, '\\textbackslash{}')
      .replace(/[&%$#_{}]/g, '\\$&')
      .replace(/~/g, '\\textasciitilde{}')
      .replace(/\^/g, '\\textasciicircum{}');
  };

  // Format date for LaTeX
  const formatDate = (dateStr: string): string => {
    if (!dateStr) return '';
    const date = new Date(dateStr);
    return date.toLocaleDateString('en-US', { month: 'long', year: 'numeric' });
  };

  let latex = `%------------------------
% LaTeX CV Template for Academic Faculty
% Generated by ZenResume
% Based on Northeastern University Faculty CV Template
%------------------------

% Document class and font size
\\documentclass[a4paper,9pt]{extarticle}

% Packages
\\usepackage[utf8]{inputenc}
\\usepackage{geometry}
\\geometry{a4paper, margin=1in}
\\usepackage{titlesec}
\\usepackage{enumitem}
\\usepackage{hyperref}
\\usepackage{changepage}

% Formatting
\\setlist{noitemsep}
\\titleformat{\\section}{\\large\\bfseries}{\\thesection}{1em}{}[\\titlerule]
\\titlespacing*{\\section}{0pt}{\\baselineskip}{\\baselineskip}
\\newenvironment{subs}
  {\\adjustwidth{2em}{0pt}}
  {\\endadjustwidth}

%-------------------------------------------------------------------------------
% Begin document
\\begin{document}

% Disable page numbers
\\pagestyle{empty}

% Header
\\begin{center}
    \\textbf{\\Large ${escapeLatex(personalInfo.fullName || 'YOUR NAME')}}\\\\[3pt]
    \\textbf{Curriculum Vitae}\\\\[1pt]
    ${personalInfo.location ? escapeLatex(personalInfo.location) + ' | ' : ''}${personalInfo.email ? `\\href{mailto:${escapeLatex(personalInfo.email)}}{${escapeLatex(personalInfo.email)}}` : ''}${personalInfo.phone ? ' | ' + escapeLatex(personalInfo.phone) : ''}
\\end{center}

`;

  // Education & Employment History Section
  latex += `%------------------------
\\section*{${escapeLatex(sectionTitles.education || 'EDUCATION \\& EMPLOYMENT HISTORY').toUpperCase()}}
    \\noindent
    \\newline
`;

  // Add education entries
  education.forEach(edu => {
    if (edu.degree || edu.school) {
      latex += `    \\textbf{${escapeLatex(edu.degree || 'Degree Name')}}${edu.field ? ` in ${escapeLatex(edu.field)}` : ''} \\\\
    ${edu.graduationDate ? `Year of completion: ${formatDate(edu.graduationDate)}` : 'Year of completion:'} \\\\ 
    ${escapeLatex(edu.school || 'Institution')} \\\\
    \\newline
`;
    }
  });

  // Add experience entries
  experiences.forEach(exp => {
    if (exp.position || exp.company) {
      latex += `    \\textbf{${escapeLatex(exp.position || 'Position Title')}} \\\\
    ${exp.startDate ? formatDate(exp.startDate) : ''}${exp.endDate ? ' - ' + formatDate(exp.endDate) : ' - Present'} \\\\
    ${escapeLatex(exp.company || 'Institution')} \\\\
    ${exp.description ? escapeLatex(exp.description) : ''} \\\\
    \\newline
`;
    }
  });

  // Publications Section
  latex += `
%------------------------
\\section*{${escapeLatex(sectionTitles.publications || 'PUBLICATIONS').toUpperCase()}}
`;

  // Group publications by type
  const pubTypes = {
    reviewed: 'Reviewed Articles',
    'non-reviewed': 'Non-Reviewed Articles',
    book: 'Books',
    chapter: 'Book Chapters',
    abstract: 'Abstracts',
    other: 'Other'
  };

  Object.entries(pubTypes).forEach(([type, title]) => {
    const pubs = publications.filter(p => p.type === type && p.citation);
    if (pubs.length > 0) {
      latex += `    \\subsection*{${title}}
`;
      pubs.forEach(pub => {
        latex += `        ${escapeLatex(pub.citation)} \\\\
        \\newline
`;
      });
    }
  });

  // If no publications, add placeholder
  if (publications.every(p => !p.citation)) {
    latex += `    Example: Author, A., \\& Author, B. (2024). Article title. \\textit{Journal Name}, 10(2), 123-145. https://doi.org/xxx
`;
  }

  // Creative Activity Section
  latex += `
%------------------------
\\section*{${escapeLatex(sectionTitles.creativeActivity || 'CREATIVE ACTIVITY').toUpperCase()}}
`;

  // Group creative works by type
  const creativeTypes = {
    publication: 'Publications',
    presentation: 'Presentations',
    performance: 'Performance',
    exhibition: 'Exhibition',
    project: 'Projects'
  };

  Object.entries(creativeTypes).forEach(([type, title]) => {
    const works = creativeWorks.filter(w => w.type === type && w.description);
    if (works.length > 0) {
      latex += `    \\subsection*{${title}}
`;
      works.forEach(work => {
        latex += `        ${escapeLatex(work.description)} \\\\
        \\newline
`;
      });
    }
  });

  // If no creative works, add placeholder
  if (creativeWorks.every(w => !w.description)) {
    latex += `    Example: Describe your creative activities, performances, exhibitions, or projects here.
`;
  }

  // Grants Section
  latex += `
%------------------------
\\section*{${escapeLatex(sectionTitles.grants || 'GRANTS').toUpperCase()}}
`;

  // External Grants
  const externalGrants = grants.filter(g => g.type === 'external');
  if (externalGrants.length > 0) {
    latex += `    \\subsection*{External Grants}
    \\begin{subs}
`;
    
    ['funded', 'pending', 'not-funded'].forEach(status => {
      const statusGrants = externalGrants.filter(g => g.status === status && g.title);
      if (statusGrants.length > 0) {
        const statusTitle = status === 'funded' ? 'Funded' : status === 'pending' ? 'Pending' : 'Not Funded';
        latex += `        \\subsubsection*{${statusTitle}}
`;
        statusGrants.forEach(grant => {
          latex += `            Proposal Title: ${escapeLatex(grant.title)} \\\\
            Funding Agency: ${escapeLatex(grant.agency)} \\\\
            Role Status: ${escapeLatex(grant.role)} \\\\
            ${grant.effort ? `Percentage of Attributed Effort: ${escapeLatex(grant.effort)} \\\\` : ''}
            ${grant.budget ? `Total direct costs: ${escapeLatex(grant.budget)} \\\\` : ''}
            ${grant.period ? `Coverage Period: ${escapeLatex(grant.period)} \\\\` : ''}
            \\newline
`;
        });
      }
    });
    
    latex += `    \\end{subs}
`;
  }

  // Internal Grants
  const internalGrants = grants.filter(g => g.type === 'internal');
  if (internalGrants.length > 0) {
    latex += `    \\subsection*{Internal Grants}
    \\begin{subs}
`;
    
    ['funded', 'pending', 'not-funded'].forEach(status => {
      const statusGrants = internalGrants.filter(g => g.status === status && g.title);
      if (statusGrants.length > 0) {
        const statusTitle = status === 'funded' ? 'Funded' : status === 'pending' ? 'Pending' : 'Not Funded';
        latex += `        \\subsubsection*{${statusTitle}}
`;
        statusGrants.forEach(grant => {
          latex += `            Proposal Title: ${escapeLatex(grant.title)} \\\\
            Funding Agency: ${escapeLatex(grant.agency)} \\\\
            Role Status: ${escapeLatex(grant.role)} \\\\
            ${grant.effort ? `Percentage of Attributed Effort: ${escapeLatex(grant.effort)} \\\\` : ''}
            ${grant.budget ? `Total direct costs: ${escapeLatex(grant.budget)} \\\\` : ''}
            ${grant.period ? `Coverage Period: ${escapeLatex(grant.period)} \\\\` : ''}
            \\newline
`;
        });
      }
    });
    
    latex += `    \\end{subs}
`;
  }

  // If no grants, add placeholder
  if (grants.every(g => !g.title)) {
    latex += `    Example grant entry with all required fields.
`;
  }

  // Teaching and Advising Section
  latex += `
%------------------------
\\section*{${escapeLatex(sectionTitles.teaching || 'TEACHING AND ADVISING').toUpperCase()}}
`;

  // Group teaching entries by type
  const courses = teachingEntries.filter(t => t.type === 'course' && t.title);
  const gradSupervision = teachingEntries.filter(t => t.type === 'grad-supervision' && t.title);
  const undergradSupervision = teachingEntries.filter(t => t.type === 'undergrad-supervision' && t.title);
  const advising = teachingEntries.filter(t => t.type === 'advising' && t.title);

  if (courses.length > 0) {
    latex += `    \\subsection*{Courses}
`;
    courses.forEach(course => {
      latex += `        ${escapeLatex(course.title)} \\\\
        ${course.details ? escapeLatex(course.details) : ''} \\\\
        \\newline
`;
    });
  }

  if (gradSupervision.length > 0) {
    latex += `    \\subsection*{Supervision of Graduate Students}
`;
    gradSupervision.forEach(student => {
      latex += `        Student Name: ${escapeLatex(student.title)} \\\\
        ${student.details ? escapeLatex(student.details) : ''} \\\\
        \\newline
`;
    });
  }

  if (undergradSupervision.length > 0) {
    latex += `    \\subsection*{Supervision of Undergraduate Students}
`;
    undergradSupervision.forEach(student => {
      latex += `        Student Name: ${escapeLatex(student.title)} \\\\
        ${student.details ? escapeLatex(student.details) : ''} \\\\
        \\newline
`;
    });
  }

  if (advising.length > 0) {
    latex += `    \\subsection*{Advising Activities}
`;
    advising.forEach(activity => {
      latex += `        ${escapeLatex(activity.title)} \\\\
        ${activity.details ? escapeLatex(activity.details) : ''} \\\\
        \\newline
`;
    });
  }

  // If no teaching entries, add placeholder
  if (teachingEntries.every(t => !t.title)) {
    latex += `    Example: Course Title, Term and Year, Number of Students
`;
  }

  // Service & Professional Development Section
  latex += `
%------------------------
\\section*{${escapeLatex(sectionTitles.service || 'SERVICE \\& PROFESSIONAL DEVELOPMENT').toUpperCase()}}
    Example: List your service to institution, discipline, and community, as well as professional development activities.

`;

  // End document
  latex += `% End document
\\end{document}
%-------------------------------------------------------------------------------
`;

  return latex;
}
